CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS web_service;

CREATE TABLE IF NOT EXISTS shared.video_courses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid         UUID         NOT NULL,
    course_id          BIGINT,
    s3key              VARCHAR(100) NOT NULL,
    extension          VARCHAR(10)  NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    thumbnail_url      VARCHAR(1000),
    encoding_status    VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at        TIMESTAMP,
    analysis_status    VARCHAR(100) NOT NULL CHECK (analysis_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    analysis_at        TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    is_deleted         BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.video_answers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid              UUID         NOT NULL,
    community_question_id   BIGINT,
    s3key                   VARCHAR(100) NOT NULL,
    extension               VARCHAR(10)  NOT NULL,
    original_file_name      VARCHAR(255) NOT NULL,
    thumbnail_url           VARCHAR(1000),
    encoding_status         VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at             TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    is_deleted              BOOLEAN      NOT NULL
    );

CREATE TABLE IF NOT EXISTS web_service.video_encodings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid      UUID          NOT NULL,
    format          VARCHAR(10)   NOT NULL,
    encoding_s3_key VARCHAR(1000) NOT NULL,
    created_at      TIMESTAMP     NOT NULL
);