CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS web_service;

-- 파일
CREATE TABLE IF NOT EXISTS web_service.files
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_type  VARCHAR(50)  NOT NULL CHECK (container_type IN ('COURSE_THUMBNAIL','COURSE_PRACTICE_FILE','ANSWER_THUMBNAIL')),
    container_id    BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    original_name   VARCHAR(255) NOT NULL,
    content_type    VARCHAR(100) NOT NULL,
    size            BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                     updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
                                     );

CREATE INDEX IF NOT EXISTS container_index
    ON web_service.files (container_type, container_id);

-- 사용자 관련
CREATE TABLE IF NOT EXISTS shared.users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(100)  NOT NULL,
    nickname           VARCHAR(30)   NOT NULL,
    password           VARCHAR(255)  NOT NULL,
    introduce          VARCHAR(4000),
    user_type          VARCHAR(15)   CHECK (user_type IN ('NONE', 'LEARNER', 'CREATOR')),
    is_deleted         BOOLEAN       NOT NULL,
    profileimage_id    BIGINT,
    deleted_at         TIMESTAMP(6) WITH TIME ZONE,
    is_email_agreed    BOOLEAN       NOT NULL,
    last_login_at      TIMESTAMP(6) WITH TIME ZONE,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- 강의 관련
CREATE TABLE IF NOT EXISTS web_service.courses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    price            INTEGER NOT NULL,
    view_count       INTEGER NOT NULL,
    like_count       INTEGER NOT NULL,
    target_audience  VARCHAR(100),
    thumbnail_id     BIGINT,
    is_show          BOOLEAN NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    is_deleted       BOOLEAN NOT NULL,
    FOREIGN KEY (user_id) REFERENCES shared.users(id),
    FOREIGN KEY (thumbnail_id) REFERENCES web_service.files(id)
);

CREATE TABLE IF NOT EXISTS web_service.course_practice_files (
    course_id   BIGINT NOT NULL,
    file_id     BIGINT NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (course_id, file_id),
    FOREIGN KEY (course_id) REFERENCES web_service.courses(id),
    FOREIGN KEY (file_id) REFERENCES web_service.files(id)
);

CREATE TABLE IF NOT EXISTS web_service.tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name    VARCHAR(50) UNIQUE NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.course_tags (
    course_id   BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (course_id, tag_id),
    FOREIGN KEY (course_id) REFERENCES web_service.courses(id),
    FOREIGN KEY (tag_id) REFERENCES web_service.tags(id)
);

CREATE TABLE IF NOT EXISTS web_service.course_install_env_checklists (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL,
    content       VARCHAR(255) NOT NULL,
    is_supported  BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.course_keypoints (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT NOT NULL,
    content     VARCHAR(500) NOT NULL
);

-- 영상 관련
CREATE TABLE IF NOT EXISTS shared.video_courses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid         UUID         NOT NULL,
    course_id          BIGINT,
    s3key              VARCHAR(100) NOT NULL,
    extension          VARCHAR(10)  NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    duration           INTEGER      NOT NULL DEFAULT 0,
    encoding_status    VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at        TIMESTAMP,
    analysis_status    VARCHAR(100) NOT NULL CHECK (analysis_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    analysis_at        TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    is_deleted         BOOLEAN      NOT NULL,
    FOREIGN KEY (course_id) REFERENCES web_service.courses(id)
);

CREATE TABLE IF NOT EXISTS web_service.video_answers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid              UUID         UNIQUE    NOT NULL,
    community_question_id   BIGINT,
    s3key                   VARCHAR(100) NOT NULL,
    extension               VARCHAR(10)  NOT NULL,
    original_file_name      VARCHAR(255) NOT NULL,
    duration                INTEGER      NOT NULL DEFAULT 0,
    encoding_status         VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at             TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    is_deleted              BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.video_encodings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid      UUID          UNIQUE   NOT NULL,
    format          VARCHAR(10)   NOT NULL,
    encoding_s3_key VARCHAR(1000) NOT NULL,
    created_at      TIMESTAMP     NOT NULL
);
