CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS web_service;

-- 영상 관련
CREATE TABLE IF NOT EXISTS shared.video_courses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid         UUID         NOT NULL,
    course_id          BIGINT,
    s3key              VARCHAR(100) NOT NULL,
    extension          VARCHAR(10)  NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    thumbnail_url      VARCHAR(1000),
    encoding_status    VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at        TIMESTAMP,
    analysis_status    VARCHAR(100) NOT NULL CHECK (analysis_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    analysis_at        TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    is_deleted         BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.video_answers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid              UUID         UNIQUE    NOT NULL,
    community_question_id   BIGINT,
    s3key                   VARCHAR(100) NOT NULL,
    extension               VARCHAR(10)  NOT NULL,
    original_file_name      VARCHAR(255) NOT NULL,
    thumbnail_url           VARCHAR(1000),
    encoding_status         VARCHAR(100) NOT NULL CHECK (encoding_status IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    encoding_at             TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    is_deleted              BOOLEAN      NOT NULL
    );

CREATE TABLE IF NOT EXISTS web_service.video_encodings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_uuid      UUID          UNIQUE   NOT NULL,
    format          VARCHAR(10)   NOT NULL,
    encoding_s3_key VARCHAR(1000) NOT NULL,
    created_at      TIMESTAMP     NOT NULL
);

-- 사용자 관련
CREATE TABLE IF NOT EXISTS shared.users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(100)  NOT NULL,
    nickname           VARCHAR(30)   NOT NULL,
    password           VARCHAR(255)  NOT NULL,
    introduce          VARCHAR(4000),
    user_type          VARCHAR(15)   CHECK (user_type IN ('NONE', 'LEARNER', 'CREATOR')),
    is_deleted         BOOLEAN       NOT NULL,
    deleted_at         TIMESTAMP(6) WITH TIME ZONE,
    is_email_agreed    BOOLEAN       NOT NULL,
    last_login_at      TIMESTAMP(6) WITH TIME ZONE,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- 강의 관련
CREATE TABLE IF NOT EXISTS web_service.courses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    price            INTEGER NOT NULL,
    view_count       INTEGER NOT NULL,
    like_count       INTEGER NOT NULL,
    target_audience  VARCHAR(100),
    thumbnail_id     BIGINT,
    is_show          BOOLEAN NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    is_deleted       BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name    VARCHAR(50) UNIQUE NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.course_tags (
    tag_id      BIGINT NOT NULL,
    course_id   BIGINT NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (course_id, tag_id)
);

CREATE TABLE IF NOT EXISTS web_service.course_install_env_checklists (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL,
    content       VARCHAR(255) NOT NULL,
    is_supported  BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS web_service.course_keypoints (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT NOT NULL,
    content     VARCHAR(500) NOT NULL
);

--커뮤니티 관련
CREATE TABLE IF NOT EXISTS web_service.community_questions (
    id INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, -- 질문 게시글 ID
    course_id INT8 NOT null references web_service.courses(id), -- 강의 ID
    title VARCHAR(255) NOT NULL, -- 질문 게시글 제목
    content TEXT NOT NULL, -- 질문 게시글 내용
    is_answered BOOLEAN NOT NULL DEFAULT FALSE, -- 답변 여부
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성 시각
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 수정 시각
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE -- 삭제 여부
);

CREATE TABLE IF NOT EXISTS web_service.community_answers (
    id INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, -- 답변 게시글 ID
    question_id INT8 NOT NULL REFERENCES web_service.community_questions(id) ON DELETE CASCADE, -- 커뮤니티 게시글 ID (질문 참조)
    content TEXT NOT NULL, -- 답변 내용
    answer_image_id INT, -- 답변 이미지 ID (nullable)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성 시각
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 수정 시각
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE -- 삭제 여부
);