package insty.model.file;

public enum FileContainerType {
    COURSE_THUMBNAIL,
    COURSE_PRACTICE_FILE,
    ANSWER_THUMBNAIL,
    USER_PROFILEIMAGE,
    QUESTION_IMAGE,
    QUESTION_CODE,
    QUESTION_LOG,
    ANSWER_IMAGE,
    COMMUNITY_POST_IMAGE,
    COMMUNITY_COMMENT_IMAGE
}
