package insty.model.file;

public enum FileContainerType {
<<<<<<< HEAD
    COURSE_THUMBNAIL, COURSE_PRACTICE_FILE, ANSWER_THUMBNAIL, QUESTION_IMAGE, QUESTION_CODE, QUESTION_LOG,
=======
    COURSE_THUMBNAIL, COURSE_PRACTICE_FILE, ANSWER_THUMBNAIL, USER_PROFILEIMAGE
>>>>>>> dev
}
