spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  security:
    jwt:
      secret: test-secret-key
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: OPTIONS,GET,POST,PUT,DELETE

  data:
    redis:
      host: test
      port: 1234

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

oauth:
  providers:
    kakao:
      endpoints:
        redirect-url: test
        token-url: https://kauth.kakao.com/oauth/token
        auth-url: https://kauth.kakao.com/oauth/authorize
        user-info-url: https://kapi.kakao.com/v2/user/me
      client-id: test
    naver:
      endpoints:
        redirect-url: test
        token-url: https://nid.naver.com/oauth2.0/token
        auth-url: https://nid.naver.com/oauth2.0/authorize
        user-info-url: https://openapi.naver.com/v1/nid/me
      client-id: test
      client-secret: test
    google:
      endpoints:
        redirect-url: test
        token-url: https://oauth2.googleapis.com/token
        auth-url: https://accounts.google.com/o/oauth2/v2/auth
        user-info-url: test
      client_id: test
      client-secret: test

app:
  health-check-path: /tmp