spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

swagger:
  server-url: ${SWAGGER_SERVER_URL}

video:
  upload:
    max-minute:
      course: 2
      answer: 2
      question: 2