spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # TODO detault 제거 개선
  security:
    jwt:
      secret: ${JWT_SECRET_KEY:test-secret-key}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: ${CORS_ALLOWED_METHODS:OPTIONS,GET,POST,PUT,DELETE}

  data:
    redis:
      host: test
      port: 1234

# TODO detault 제거 개선
oauth:
  providers:
    kakao:
      endpoints:
        redirect-url: test
        token-url: https://kauth.kakao.com/oauth/token
        user-info-url: https://kapi.kakao.com/v2/user/me
      client-id: test


app:
  health-check-path: /tmp