spring:
  profiles:
    default: dev

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region:
    static: ${AWS_REGION}
  s3-upload-bucket: ${AWS_S3_UPLOAD_BUCKET}

  cloudfront:
    key-pair-id: ${AWS_CLOUDFRONT_KEY_PAIR_ID}
    private-key-path: ${AWS_CLOUDFRONT_PRIVATE_KEY_PATH}

app:
  domain: ${INSTY_DOMAIN}