dependencies {
    implementation project(':insty-common')
    implementation project(':insty-domain')
    implementation project(':insty-external')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // JpaConfig 전용
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'org.springframework.boot:spring-boot-starter-aop' // AOP를 통한 Log 저장(mixpanel)
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.3' // JSON Mapper

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation(testFixtures(project(':insty-domain')))
    testImplementation 'com.h2database:h2'
    runtimeOnly 'com.h2database:h2'
}

tasks.register('unitTest', Test) {
    useJUnitPlatform {
        includeTags 'unit'
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}

tasks.register('integrationTest', Test) {
    useJUnitPlatform {
        includeTags 'integration'
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}